### ISSUE TITLE
Опечатка в async_python/coroutines

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#1]
[Anton Demkin]
Привет. Небольшой багрепорт по статье.
[По ссылке](https://devman.org/encyclopedia/async_python/coroutines/#parallelism) нашел опечатку.

> "Если список с корутинами закончился (его длинна равна нулю), пора заканчивать и бесконечный цикл, потому что все файлы скачаны."

**Comment by keinen87** [comment]
Было:
![image](https://user-images.githubusercontent.com/14131872/75853608-f071e700-5e07-11ea-80af-c268c9606576.png)

Стало:
![image](https://user-images.githubusercontent.com/14131872/75853668-07183e00-5e08-11ea-9fe1-ad5300075892.png)
