### ISSUE TITLE
Починить первый урок ORM

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#10]
Урок невозможно пройти в Repl. Сервис сначала не даёт импортировать код из репозитория в Repl, потом не запускается из-за файла`requirements.txt`. Затронуты сразу два репозитория с кодом

- [Django-ORM-standalone](https://github.com/dvmn-tasks/Django-ORM-standalone)
- [django-orm-watching-storage](https://github.com/dvmn-tasks/django-orm-watching-storage)

Чего хочется:

1. Не тратить время ученика на борьбу с Repl, тем более что это первый урок модуля
2. Надёжное решение, которое не сломается даже если разрабы Repl снова придумают способ всех развлечь.

Хорошим решением видится Fork нашего шаблонного Repl.

@voron434 эта issue твоя, почини её в срочном порядке.

Что надо сделать после решения проблемы:

1. Я сам тщательно протестирую первый урок
2. Проверить остальные уроки с Repl — что код запускается
3. В соц.сети надо сделать анонс для тех, кто застрял в ORM из-за репла

**Comment by voron434** [comment]
Добавил `pyproject.toml` и `poetry.lock`, теперь в репле запускаются.

`requirements.txt` убирать не стал, для тех кто на своём компьютере решают. Тем более реплу он не мешает.
