### ISSUE TITLE
Яндекс не пускает отправлять письма, если не привязан телефон

### ISSUE THREAD

**Issue by voron434** [devmanorg/course#12]
В третьем уроке "Знакомство с Python" мы предлагаем отправлять письма с новой почты yandex.ru. Планировалось, что ученик создаст почту, пароль от которой не жалко спалить и отправит с неё сообщение на любую другую.

Есть 2 предложения как решить проблему:

1. Найти другой сервис, с которого можно рассылать письма
2. Дать им свой аккаунт, от имени которого они будут рассылать письма.

В идеале, если выберем второй вариант, можно это сюжетно обыграть: в истории сказать, что это рассылка от имени компании и именно поэтому нужно рассылать письма с "корпоративной" почты.

**Comment by pelid** [comment]
Еще вариант — пусть привяжут свой номер телефона. В интернете все борятся со спамом и подтверждение identity и регистрации почты — это нормальная практика. Не вижу в ней ничего зазорного.

**Comment by pelid** [comment]
Ещё можно поставить свой сервис для рассылки почты, чтобы он разрешал email рассылку только по ограниченному количеству email адресов. Но это кажется сложным в реализации решением.

**Comment by pelid** [comment]
@voron434 Расскажи подробнее про кейсы. Почему они номер телефона не привязывают? Это их осознанный выбор?

**Comment by voron434** [comment]
> @voron434 Расскажи подробнее про кейсы. Почему они номер телефона не привязывают? Это их осознанный выбор?

Потому что в этом уроке они тренируются прятать ключи. В процессе решения и даже при сдаче работы они могут неправильно это сделать и логин-пароль он их яндекс-почты утечёт в сеть.

Так как у многих учеников наверняка почта на яндексе -- основная, это будет большой потерей для них.

**Comment by dvmn-tasks** [comment]
Добавил совет, выделил почту под такие нужды.

В шаг её добавлять не хочу, чтобы контролировать кому и когда она попадает в руки.

![image](https://user-images.githubusercontent.com/44063469/78997452-447e9280-7b4f-11ea-889e-593c3e437418.png)
