### ISSUE TITLE
Не понятна статья про .env

### ISSUE THREAD

**Issue by voron434** [devmanorg/course#14]
В 3ем уроке знакомства они сталкиваются с `.env`, который объясняется на примере токена, но что такое токен они не знают.

**Comment by keinen87** [comment]
На википедии есть большая [статья](https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BA%D0%B5%D0%BD_(%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8)#%D0%A2%D0%BE%D0%BA%D0%B5%D0%BD_%D0%B8_%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8_%D0%B5%D0%B4%D0%B8%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B2%D1%85%D0%BE%D0%B4%D0%B0) по токену.

**Comment by voron434** [comment]
Имхо, отостой, т.к. если не знать о чём речь ничего понять будет невозможно. В целом болезнь многих статей на википедии.

Нужно найти что-то другое.

**Comment by keinen87** [comment]
Предлагаю просто дописать в [гист](https://gist.github.com/dvmn-tasks/22b18aafb24a6be5213eb5c6532eaef8) на [8 шаге](https://dvmn.org/modules/meeting-python/lesson/friend-invitation/#8) упоминание, что такое токен.

**Comment by keinen87** [comment]
Убрал вообще упоминание о нём.
