### ISSUE TITLE
Баг в гифке результата первого урока API

### ISSUE THREAD

**Issue by voron434** [devmanorg/course#19]
По задаче они локализовали погоду в Цельсии и км/ч, а на гифке результата погода в фаренгейтах и милях в час.

Есть небольшая путаница с тем, какие параметры в решении нужны, а какие нет. Нужно зафиксировать каноническое решение.

**Comment by Kingoff8** [comment]
Где эти уроки посмотреть можно?

**Comment by keinen87** [comment]
Перезалил гифку

**Comment by keinen87** [comment]
> Где эти уроки посмотреть можно?

https://dvmn.org/modules/
Модуль API веб-сервисов
