### ISSUE TITLE
SMM, 1 задача, переезд на новую версию Plotly

### ISSUE THREAD

**Issue by voron434** [devmanorg/course#20]
Мы перевели задачу на новую версию Plotly, но нужно её перерешать и проверить, что всё работает точно так же, как было.

**Comment by keinen87** [comment]
Решение [5-го шага](https://dvmn.org/modules/python-for-smm/lesson/vk-analytics/#5) сводится к копипасте из [слайдов](https://slides.dvmn.org/voron434/datetime/#/3).

**Comment by voron434** [comment]
> Решение [5-го шага](https://dvmn.org/modules/python-for-smm/lesson/vk-analytics/#5) сводится к копипасте из [слайдов](https://slides.dvmn.org/voron434/datetime/#/3).

ну это надо разобраться в datetime и понять ещё что копипастить. не вижу в этом проблемы, с datetime они толком сталкиваются первый раз в этом уроке.
