### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by voron434** [devmanorg/course#27]
Считываются с помощью ВСТРЕНЕОГО модуля os

https://gist.github.com/dvmn-tasks/22b18aafb24a6be5213eb5c6532eaef8

**Comment by keinen87** [comment]
Было:
![image](https://user-images.githubusercontent.com/14131872/75951488-920b3e00-5ec5-11ea-8edd-a5a98fbd0d23.png)

Стало:
![image](https://user-images.githubusercontent.com/14131872/75951528-aa7b5880-5ec5-11ea-9c38-22a8c9a0125e.png)
