### ISSUE TITLE
API. Урок 4, переставить шаги местами

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#3]
![image](https://user-images.githubusercontent.com/870324/75696067-06729100-5cbc-11ea-861e-d2db774961bd.png)

![image](https://user-images.githubusercontent.com/870324/75696081-0d999f00-5cbc-11ea-8bd6-412530b84bb8.png)

Sult, [01.03.20 21:11]
Думаю его надо поставить сразу после 10го шага
Так логичнее

**Comment by keinen87** [comment]
Исправлено:
![image](https://user-images.githubusercontent.com/14131872/75854333-675baf80-5e09-11ea-9949-412f74b492c6.png)
