### ISSUE TITLE
Перенести все уроки с Repl.it на использование форков

### ISSUE THREAD

**Issue by keinen87** [devmanorg/course#30]
В очередной раз возникли проблемы с установкой библиотеки transliterate в Repl.it. Причём в этот раз сломался основной их графический интерфейс для установки через список пакетов. Выдает невнятную внутреннюю ошибку, не связанную с Python.

Та же проблема возникла с установкой asciimatics.

> Evgeny Evseev, [07.03.20 16:19]
> Я ввожу запрет на использовании в уроках фич Repl "Установить пакет" и "Импортировать репо с GitHub". Первая работает нестабильно, приводит к плавающим ошибкам и не даёт зафиксировать версию библиотеки. Вторая тоже нестабильна, а прямо сейчас у меня вообще не работает.
> 
> Остается один способ — форк репла. Его и будем использовать во всех уроках. Старые надо переписать

TODO:

- [x] Создать на Repl общий аккаунт, там будем хранить заготовки кода
- [x] Из всех шагов выпилить инструкции по установке библиотек в Repl.it, предложить форкнуть наш код - заготовку на Repl.it
- [x] Написать туториал _Как форкнуть код на Repl_
- [x] Добавить туториал _Как форкнуть код на Repl_ во все шаги, где мы просим сделать форк

**Comment by pelid** [comment]
@keinen87 туториал беру на себя, позже пришлю ссылку.

**Comment by keinen87** [comment]
### [Урок 2. Готовим речь](https://dvmn.org/modules/meeting-python/lesson/preparing-speech/)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76316507-275a6800-62f4-11ea-8358-9130e89e7952.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76316637-5e307e00-62f4-11ea-9744-905ec0298d3d.png)

**[Было](https://gist.github.com/keinen87/3bf666a51cca4e2b039e6c136d05b68e)**:
![image](https://user-images.githubusercontent.com/14131872/76305875-6205d580-62df-11ea-9cc0-b9212a2ba3dd.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76394997-d8621080-638f-11ea-97fd-2c5b2aaf64ee.png)

**Comment by keinen87** [comment]
### [Урок 4. Нарезаем аватарки](https://dvmn.org/modules/meeting-python/lesson/avatar-cropping/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76317796-2de9df00-62f6-11ea-8f0a-46339ca47686.png)
![image](https://user-images.githubusercontent.com/14131872/76317721-101c7a00-62f6-11ea-8ea7-32f1697ddaa1.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76395215-3858b700-6390-11ea-9656-4f1e0216d9a9.png)

**Comment by keinen87** [comment]
### [Урок 5. Считаем секунды в Telegram](https://dvmn.org/modules/meeting-python/lesson/timer-in-telegram/)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76318738-98e7e580-62f7-11ea-9d0e-3c20a79517dd.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76396005-ddc05a80-6391-11ea-9bcb-9d4fcdfec79f.png)

**Comment by keinen87** [comment]
### [Урок 6. Создаём человеков](https://dvmn.org/modules/meeting-python/lesson/fake-people/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76396269-4c9db380-6392-11ea-98f9-83b7a761e1ad.png)

**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76396903-8a4f0c00-6393-11ea-888a-73c26c356965.png)

**Comment by keinen87** [comment]
### [Урок 7. Оцениваем пароли](https://dvmn.org/modules/meeting-python/lesson/password-strength/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76399214-b10f4180-6397-11ea-8102-8253331f2234.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76399355-e87dee00-6397-11ea-86f6-6ab1eb0fd9aa.png)

**Comment by keinen87** [comment]
### [Урок 8. Ищем где выпить](https://dvmn.org/modules/meeting-python/lesson/bars-search/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76407260-837cc500-63a4-11ea-81f2-3acab49d871f.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76407331-a018fd00-63a4-11ea-8c83-5a3a323c9a1f.png)

**Comment by pelid** [comment]
:+1:
@keinen87 Сколько ещё уроков осталось поправить?

**Comment by keinen87** [comment]
> @keinen87 Сколько ещё уроков осталось поправить?

@pelid 
- [x] 1 урок по "Django ORM"
- [x] 2 урок по "Работа с соцсетями"
- [x] 3 урок по "Работа с соцсетями"
- [x] 5 урок по "Работа с соцсетями"
- [x] 1 урок по "Чат-боты"
- [x] 3 урок по "Чат-боты"
- [x] 4 урок по "Чат-боты"
- [x] 5 урок по "Чат-боты"
- [x] 6 урок по "Чат-боты"
- [x] 1 урок по "Асинхронный Python"

**Comment by keinen87** [comment]
### [Урок 1. Пишем пульт охраны банка](https://dvmn.org/modules/django-orm/lesson/watching-storage/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76412363-ea9e7780-63ac-11ea-8f98-e1659d8e1820.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76412956-00606c80-63ae-11ea-84f4-d406f04c4233.png)

**Comment by keinen87** [comment]
### [Урок 2. Создайте инструмент для конкурсов в Instagram](https://dvmn.org/modules/python-for-smm/lesson/insta-advertising/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76415649-fe4cdc80-63b2-11ea-8f80-72bfa0dcaba8.png)

**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76416446-8d0e2900-63b4-11ea-9343-71effb5022cd.png)

**Comment by keinen87** [comment]
### [Урок 3. Опубликуйте посты во всех соцсетях](https://dvmn.org/modules/python-for-smm/lesson/smm-reposting/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76417704-c5af0200-63b6-11ea-99df-fabdc0bdd05d.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76418818-bd57c680-63b8-11ea-8bea-78525c64e431.png)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76418395-ff343d00-63b7-11ea-9dee-ad4c6c8ccebd.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76419029-1b84a980-63b9-11ea-9ff9-6762400a2902.png)

**Comment by keinen87** [comment]
### [Урок 5. Напишите свой Амплифер](https://dvmn.org/modules/python-for-smm/lesson/customer-searching/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76422115-22fa8180-63be-11ea-88e1-57ad1a80c721.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76422839-483bbf80-63bf-11ea-82de-2e3bf2335bba.png)

**Comment by keinen87** [comment]
### [Урок 1. Отправляем уведомления о проверке работ](https://dvmn.org/modules/chat-bots/lesson/devman-bot/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76448403-b4c8b580-63e3-11ea-9cdc-3623e10b3340.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76449182-0de51900-63e5-11ea-970c-2a99e34bc770.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76449408-78965480-63e5-11ea-8e35-38a0d7e5ff9e.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76449807-26a1fe80-63e6-11ea-86c9-e33e92335522.png)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76449961-6f59b780-63e6-11ea-9a4c-34b7a6b6a4d5.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76450260-e5f6b500-63e6-11ea-8bae-037d91441527.png)

**Comment by keinen87** [comment]
### [Урок 3. Распознаём речь](https://dvmn.org/modules/chat-bots/lesson/support-bot/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76451475-e7c17800-63e8-11ea-8603-72ab6962328a.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76452646-e5601d80-63ea-11ea-802e-21287d061133.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76453093-9f578980-63eb-11ea-9c40-37662acb0ef8.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76547006-ea35d780-64a5-11ea-80f1-f018ab0d01a2.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76547089-0df91d80-64a6-11ea-9417-7436be7136c9.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76547247-4ef13200-64a6-11ea-8e15-6f6d2d2efd34.png)

**Comment by keinen87** [comment]
### [Урок 4. Проводим викторину](https://dvmn.org/modules/chat-bots/lesson/quiz-bot/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76453913-22c5aa80-63ed-11ea-8f79-2dff9f9c5903.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76454520-42110780-63ee-11ea-8298-1bb71f2d796c.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76454942-bfd51300-63ee-11ea-918b-bffbe3412267.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76455389-20645000-63ef-11ea-8896-5197cb54aff6.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76455625-51448500-63ef-11ea-9aaf-260510b0624f.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76455839-97014d80-63ef-11ea-898c-47a41635edb0.png)
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76456155-09722d80-63f0-11ea-8d7a-f3fec83b1cb4.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76547776-32092e80-64a7-11ea-8d86-3b85e98de963.png)

**Comment by keinen87** [comment]
### [Урок 5. Продаём рыбу в Telegram](https://dvmn.org/modules/chat-bots/lesson/fish-shop/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76490900-bcb94180-6445-11ea-830b-396182fd77b7.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76491387-fa6a9a00-6446-11ea-92d7-416a16180df5.png)

**Comment by keinen87** [comment]
### [Урок 6. Принимаем платежи за пиццу](https://dvmn.org/modules/chat-bots/lesson/pizza-bot/)

**Было**:
![image](https://user-images.githubusercontent.com/14131872/76495119-a9ab6f00-644f-11ea-9b10-e7ee6e6ba2a1.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76495380-2dfdf200-6450-11ea-9f9b-bd6ef284b92f.png)

**Comment by keinen87** [comment]
### [Урок 1. Делаем игру про космос](https://dvmn.org/modules/async-python/lesson/async-console-game/)

Заготовка не нужна, т.к. используется стандартная библиотека.
**Было**:
![image](https://user-images.githubusercontent.com/14131872/76496600-db720500-6452-11ea-8ade-9d1863fb833a.png)
**Стало**:
![image](https://user-images.githubusercontent.com/14131872/76496654-efb60200-6452-11ea-8fbe-bee2fec7ad66.png)

**Comment by keinen87** [comment]
### [Урок 2. Сквозь мусор к звёздам](https://dvmn.org/modules/async-python/lesson/async-console-game-2/)

**Comment by keinen87** [comment]
### [Урок 3. А скинешь фоточки?](https://dvmn.org/modules/async-python/lesson/download-photos/)

**Comment by keinen87** [comment]
### [Урок 4. Подключаемся к подпольному чату](https://dvmn.org/modules/async-python/lesson/underground-chat-cli/)
