### ISSUE TITLE
Починить шаблон блога

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#32]
Урок 2. Оживляем блог на Django" в модуле про "Вёрстка для питониста".

На странице `blog-details.html` в разметке встречается такой фрагмент:

```html
<a href="#"><h4>Заголовок поста</h4></a>
```

Проблема в том, что `blog-details.html` — это как раз страница поста и ссылке вести некуда, разве что на эту же страницу.

![image](https://user-images.githubusercontent.com/870324/76260895-de5dd180-6269-11ea-9948-b6b23d49d7ce.png)

Думаю, что ссылки здесь просто быть не должно, достаточно заголовка h4.

**Comment by keinen87** [comment]
перезалил архив
