### ISSUE TITLE
Добавить шаг в 1 урок по вёрстке 

### ISSUE THREAD

**Issue by keinen87** [devmanorg/course#34]
[Урок 1. Продаём элитное вино](https://dvmn.org/modules/website-layout-for-pydev/lesson/wine-shop/)

Так как в [новом файле](https://dvmn.org/filer/canonical/1579542975/475/) группы продукции даны вразноброс, нужно добавить отдельный шаг про использование `defaultdict` и сортировку в нужном Розе порядке.

**Comment by keinen87** [comment]
https://gist.github.com/keinen87/7c1181a44c994b78db1b6daef8bb6c88

**Comment by keinen87** [comment]
@voron434

**Comment by voron434** [comment]
Я решал задачу без него и если честно вообще не вижу в нём надобности.
Вот моё решение этого шага, имхо, довольно простое (один for и один if):
![image](https://user-images.githubusercontent.com/25554602/77914829-25564a00-729f-11ea-8d90-a0aa2752417d.png)

**Comment by keinen87** [comment]
@pelid

**Comment by dvmn-tasks** [comment]
Договорились на том, что DefaultDict слишком хорошо подходит для ситуации, чтобы про него не рассказать.

Предложение: сразу после 11 шага добавляем шаг как в этом гисте, но в шаге defaultdict не советуем, пусть распарсят через for + if

> https://gist.github.com/keinen87/7c1181a44c994b78db1b6daef8bb6c88

Дальше ещё один шаг, "Воспользуйтесь DefaultDict", где в мотивации написано что это и зачем оно, в цели "у вас пропадёт один if", а в "что понадобится" -- ссылки что это такое.

И дальше уже тот шаг, который сейчас 12ый.
