### ISSUE TITLE
Починить битую ссылку в 4 уроке Знакомства с Python

### ISSUE THREAD

**Issue by keinen87** [devmanorg/course#35]
В [3 шаге](https://dvmn.org/modules/meeting-python/lesson/avatar-cropping/#3) не открывается 3-я ссылка в "Что понадобится":
- [Что такое RGB](https://webgyry.info/rgb-format)

Временно заменил на другую

**Comment by keinen87** [comment]
@voron434

**Comment by voron434** [comment]
Норм, статья очень повторяется, но слова все понятные.
