### ISSUE TITLE
Перевести первый урок API на Repl.it

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#43]
Урок *Получите погоду из терминала* сейчас использует встроенный редактор кода и свой Docker контейнер для запуска кода. Это последний урок на сайте, использующий такой редактор. Если переведём его на Repl.it, то сможем отказаться от поддержки этой функциональности.

**Comment by keinen87** [comment]
Сделать переходную версию. Пока прохождение урока тремя вариантами - встроенным контейнером, реплом и на своей машине(гитхаб)
