### ISSUE TITLE
Выпилить "мы" из шагов первого урока ORM

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#5]
![image](https://user-images.githubusercontent.com/870324/75703661-ebf2e480-5cc8-11ea-998c-74e644221f01.png)
В шагах урока хорошие текстовки, но автор постоянно словно влезает в мой код всякими "мы" и "давайте сделаем вместе" . Словно это не я пишу код, а автор урока. Это разрушает эффект погружения в историю и проект.

Хочет поправить все текстовки, чтобы там больше не было никаких "мы". Есть только Я — ученик и есть заказчики учебного проекта: бухгалтер Валентин и безымянный охранник.

[Ссылка на урок](https://dvmn.org/modules/django-orm/lesson/watching-storage/)

**Comment by keinen87** [comment]
![lesson3_nav_screenshot](https://user-images.githubusercontent.com/14131872/75755509-32d3ef00-5d48-11ea-8003-758bbb575d6e.PNG)

**Comment by keinen87** [comment]
2 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847749-7a668380-5df9-11ea-86b7-d5ca630ad8dc.png)

2 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75850146-fbc11480-5dff-11ea-87cd-8b79a0a9cda6.png)

3 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847770-85b9af00-5df9-11ea-97ad-f340567f9233.png)

3 шаг Стало:
![image](https://user-images.githubusercontent.com/14131872/75851317-c23dd880-5e02-11ea-8289-ba2cda7867be.png)

5 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847786-90744400-5df9-11ea-9a10-d59eb2d2510b.png)

5 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75950294-34292700-5ec2-11ea-8713-89383a962402.png)

6 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847796-9d913300-5df9-11ea-8c26-4733356daebf.png)

6 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75950336-486d2400-5ec2-11ea-9a71-785b3167cea0.png)

8 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847817-a8e45e80-5df9-11ea-9832-9ba6198158a7.png)

8 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75950349-5753d680-5ec2-11ea-9caf-71ae818a57f7.png)

13 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847838-bc8fc500-5df9-11ea-8437-14a4561419ba.png)

13 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75950371-6dfa2d80-5ec2-11ea-9c84-807842e1e074.png)

14 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847856-c7e2f080-5df9-11ea-8cdc-3ab3781f9c16.png)

14 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75950392-7bafb300-5ec2-11ea-8c9b-396d09f75287.png)

15 шаг. Было:
![image](https://user-images.githubusercontent.com/14131872/75847882-e3e69200-5df9-11ea-89c3-276c3bc165ea.png)

15 шаг. Стало:
![image](https://user-images.githubusercontent.com/14131872/75851407-05984700-5e03-11ea-861f-27988818773d.png)
