### ISSUE TITLE
Починить урок с instabot

### ISSUE THREAD

**Issue by pelid** [devmanorg/course#54]
conformíst, [09.06.20 01:24]
[Forwarded from Валерий Моисеев]
Привет!

У меня вопрос по уроку Урок 4. Загрузите в Instagram фотографии космоса. Опубликуйте любую фотографию в Instagram

Опубликуйте любую одну фотографию в ваш аккаунт. В этом вам поможет библиотека instabot. Она упрощает взаимодействие с Instagram.

Репозиторий instabot (https://github.com/instagrambot/instabot) архивирован, также в markdown'e написано
This code is no longer maintaned. Don't try to run anything from here - you will be easily detected and banned by Instagram.

Join our Telegram community to find more tools, projects and growth hacking methods.

Read why you shouldn't run any bots: it is no longer safe.

Вопрос, что делать в таком случае?

**Comment by voron434** [comment]
Добавил пояснение насчёт этого предупреждения, библиотека пока что работает.

Также написал, что если перестанет -- пусть пишут куратору.
