### ISSUE TITLE
Нерабочая ссылка в 1 шаге урока "Оцениваем пароли"  модуля "Знакомство с Python"

### ISSUE THREAD

**Issue by keinen87** [devmanorg/course#64]
[Шаг](https://dvmn.org/modules/meeting-python/lesson/password-strength/#1)
Ссылка [Ввод и вывод данных в Python](http://www.tryobj.com/72-oprog-27.html)

**Comment by voron434** [comment]
Починил:

- [Функция `input()`](https://pythonz.net/references/named/input/)
    - [Запасная статья](https://devpractice.ru/python-lesson-12-input-output-work-with-files/), если не очень понятно
